/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativelib_NdkManager */

#ifndef _Included_nativelib_NdkManager
#define _Included_nativelib_NdkManager
#ifdef __cplusplus

extern "C" {
#endif
/*
 * Class:     com_example_mathcalculator_NdkManager
 * Method:    determinantOfMatrix
 * Signature: (I[D)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_mathcalculator_NdkManager_determinantOfMatrix
  (JNIEnv *, jobject, jint, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
